name: sms_handler
description: "SMS Handler Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_sms_inbox: ^1.0.3  # For SMS handling
  permission_handler: ^11.3.0  # For handling permissions
  http: ^1.2.0  # For making API calls

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # For generating app icons


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/


# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app_icon.png"
  remove_alpha_ios: true
